server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      routes:
        - id: auth-route
          uri: http://localhost:8085
          predicates:
            - Path=/auth/**

jwt:
  secret: "b65ae463fb83f3f8fbc7a06ab440016eccc07c2aebfa9bc11709093894f4773f"
